name: daily-cron
on:
  schedule:
    - cron: "11 19 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://update-nu.vercel.app/api/hello' \

# --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
